### ISSUE TITLE
多智能体强化学习算法能不能在除了SMAC的环境上跑呢?

### ISSUE THREAD

**Issue by ggggfff1** [opendilab/DI-engine-docs#224]
SMAC环境安装比较复杂且对计算机要求较高,如果只是想体验下多智能体算法有没有简单一点的环境?

**Comment by PaParaZz1** [comment]
可以的，多智能体的简单 demo 可以从 PettingZoo 中提供的 mpe_simple_spread 入手，具体文档参考[传送门](https://di-engine-docs.readthedocs.io/zh_CN/latest/13_envs/pettingzoo_zh.html)
